quarkus:
  swagger-ui:
    always-include: 'true'
    enable: 'true'
    path: /send
  openshift:
    env:
      vars:
        kafka-bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-cluster-dev-kafka-bootstrap.kafka-dev.svc.cluster.local:9092}
        kafka-topic: ${KAFKA_TOPIC:payload}
    route:
      expose: 'true'
    deploy: 'true'
  kubernetes-client:
    trust-certs: 'true'
  http:
    non-application-root-path: /
  s2i:
    base-jvm-image: registry.access.redhat.com/ubi8/openjdk-11
